services:
  
  mongodb:
    build: ./mongodb
    image: mongodb:v1
    container_name: mongodb
    volumes:
      - mongodb:/data/db
 
  redis:
    build: ./redis
    image: redis:v1
    container_name: redis
    volumes:
      - redis:/data

  rabbitmq:
    build: ./rabbitmq
    image: rabbitmq:v1
    container_name: rabbitmq
    volumes:
      - rabbitmq:/var/lib/rabbitmq

  mysql:
    build: ./mysql
    image: mysql:v1    
    container_name: mysql
    volumes:
    - mysql:/var/lib/mysql

  
  
  

  catalogue:
    build: ./catalogue
    image: catalogue:v1
    container_name: catalogue

  
  shipping:
    build: ./shipping
    image: shipping:v1
    container_name: shipping

  cart:
    build: ./cart
    image: cart:v1
    container_name: cart

  user:
    build: ./user
    image: user:v1
    container_name: user

  
  payment:
    build: ./payment
    image: payment:v1
    container_name: payment


  frontend:
    build: ./frontend
    image: frontend:v1
    container_name: frontend
    ports:
      - "80:80"

networks:
  default:
   driver: bridge
   name: roboshop
   external: false

volumes:
  mongodb:
  redis:
  rabbitmq:
  mysql:

